server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-registration
    username: root
    password: Amadeus2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailtrap.io
    protocol: smtp
    port: 2525
    username: c3e71eae6d4354
    password: 29d5f47eb16bbd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: api.read
            client-name: api-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000

#  registration in line 29 is our name.
#  api-client-oidc is our registrationId. .redirectUri("http://127.0.0.1:8080/login/oauth2/code/api-client-oidc")
#  we have picked up 32-34 from the authorization server's AuthorisationServerConfig